[package]
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "biome_rule_options"
repository.workspace = true
version = "0.0.1"

[dependencies]
biome_deserialize = { workspace = true }
biome_deserialize_macros = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
biome_rowan = { workspace = true }
regex = { workspace = true }
smallvec = { workspace = true }
enumflags2 = { workspace = true }

[lints]
workspace = true


[features]
schema = ["dep:schemars"]
